ARDUINO_DIR = /usr/share/arduino/
AVR_TOOLS_DIR = ../ide-arduino/hardware/tools/avr
ARDMK_DIR = ../arduino-makefile
BOARDS_TXT = ../ide-arduino/hardware/arduino/avr/boards.txt
ARDUINO_QUIET = 1
include ../arduino-makefile/Arduino.mk
